from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from code.config import ensure_directories, path_in_project
from code.experiments_synthetic import run_synthetic_experiments


def _count_files(folder, suffixes=None):
    p = path_in_project(folder)
    if not p.exists():
        return 0
    if suffixes is None:
        return sum(1 for item in p.rglob('*') if item.is_file())
    return sum(1 for item in p.rglob('*') if item.is_file() and item.suffix.lower() in suffixes)


def _apply_profile(config_path: str, profile: str | None) -> tuple[str, str]:
    """Optionally materialize a temporary config with a selected execution profile."""
    if not profile:
        return config_path, 'config_default'
    path = path_in_project(config_path)
    with path.open('r', encoding='utf-8') as f:
        config = json.load(f)
    profiles = config.get('profiles', {})
    if profile not in profiles:
        raise ValueError(f"Unknown profile '{profile}'. Available profiles: {', '.join(sorted(profiles))}")
    profile_cfg = profiles[profile]
    for key, value in profile_cfg.items():
        if isinstance(value, dict) and isinstance(config.get(key), dict):
            config[key].update(value)
        else:
            config[key] = value
    config['execution_profile'] = profile
    config['active_execution_profile'] = profile
    tmp = path_in_project(f'configs/_active_{profile}_config.json')
    with tmp.open('w', encoding='utf-8') as f:
        json.dump(config, f, ensure_ascii=False, indent=2)
    return str(tmp.relative_to(path_in_project('.'))), profile


def main(argv: list[str] | None = None):
    parser = argparse.ArgumentParser(description='Run the synthetic public-good free-riding modeling project.')
    parser.add_argument('--config', default='configs/synthetic_config.json', help='Path to the JSON configuration file.')
    parser.add_argument('--profile', choices=['quick', 'paper'], default=None, help='Optional execution profile for reproducibility checks.')
    parser.add_argument('--no-figures', action='store_true', help='Skip figure regeneration and only write numerical CSV outputs.')
    args = parser.parse_args(argv)

    ensure_directories()
    active_config, profile_label = _apply_profile(args.config, args.profile)
    status = {
        'started_at_utc': datetime.now(timezone.utc).isoformat(),
        'mode': 'synthetic_only',
        'entry_point': 'main.py',
        'config': active_config,
        'execution_profile': profile_label,
        'figures_requested': not args.no_figures,
    }

    run_synthetic_experiments(config_path=active_config, generate_figures=not args.no_figures)

    status['synthetic'] = 'completed'
    status['figures'] = 'regenerated by main.py' if not args.no_figures else 'skipped by --no-figures'
    status['finished_at_utc'] = datetime.now(timezone.utc).isoformat()

    logs_dir = path_in_project('logs/experiment_logs')
    logs_dir.mkdir(parents=True, exist_ok=True)
    with (logs_dir / 'run_summary.json').open('w', encoding='utf-8') as f:
        json.dump(status, f, ensure_ascii=False, indent=2)

    print('\nPublicGood_FreeRiding run summary')
    print(json.dumps(status, indent=2))
    print(f"Project root: {path_in_project('.').resolve()}")
    print(f"Results directory: {path_in_project('results').resolve()}")
    print(f"Figures directory: {path_in_project('figs').resolve()}")
    print(f"Processed synthetic data directory: {path_in_project('data/processed/synthetic').resolve()}")
    print(f"CSV files generated/found: {_count_files('results', {'.csv'}) + _count_files('data/processed', {'.csv'}) + _count_files('report_assets', {'.csv'})}")
    print(f"Figure files generated/found: {_count_files('figs', {'.svg', '.png', '.pdf'})}")
    return status


if __name__ == '__main__':
    try:
        main()
    finally:
        sys.stdout.flush()
        sys.stderr.flush()
